"""memories and thread digests

Revision ID: 93a005eb04c2
Revises: 9240f67d1d12
Create Date: 2026-09-21 07:12:47.987750+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '93a005eb04c2'
down_revision: Union[str, None] = '9240f67d1d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('source_thread_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_hash'), 'memories', ['hash'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('thread_digests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('stale_turns', sa.Integer(), nullable=False),
    sa.Column('last_turn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_digests_thread_id'), 'thread_digests', ['thread_id'], unique=True)
    op.create_index(op.f('ix_thread_digests_user_id'), 'thread_digests', ['user_id'], unique=False)

    op.execute(
        "CREATE INDEX ix_memories_embedding_hnsw ON memories "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_thread_digests_embedding_hnsw ON thread_digests "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_memories_content_fts ON memories "
        "USING gin (to_tsvector('simple', content))"
    )
    op.execute(
        "CREATE INDEX ix_thread_digests_fts ON thread_digests "
        "USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || digest))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_thread_digests_fts")
    op.execute("DROP INDEX IF EXISTS ix_memories_content_fts")
    op.execute("DROP INDEX IF EXISTS ix_thread_digests_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_memories_embedding_hnsw")
    op.drop_index(op.f('ix_thread_digests_user_id'), table_name='thread_digests')
    op.drop_index(op.f('ix_thread_digests_thread_id'), table_name='thread_digests')
    op.drop_table('thread_digests')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_hash'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
